CREATE TABLE LEETCODE_ACCOUNT (
    username VARCHAR(100) PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE DISCORD_ACCOUNT (
    username VARCHAR(100) PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE SUBSCRIPTION (
    leetcode_id VARCHAR(100),
    discord_id VARCHAR(100),
    PRIMARY KEY (leetcode_id, discord_id),
    FOREIGN KEY (leetcode_id) REFERENCES LEETCODE_ACCOUNT(username),
    FOREIGN KEY (discord_id) REFERENCES DISCORD_ACCOUNT(username)
);
CREATE TABLE AC_COMPLETION (
    ac_id VARCHAR(100) PRIMARY KEY,
    leetcode_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);