CREATE TABLE LEETCODE_ACCOUNT (
    id VARCHAR(100) PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE DISCORD_ACCOUNT (
    id VARCHAR(100) PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE GUILD (
    id VARCHAR(100) PRIMARY KEY,
    guild_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE SUBSCRIPTION (
    leetcode_id VARCHAR(100),
    discord_id VARCHAR(100),
    guild_id VARCHAR(100),
    PRIMARY KEY (leetcode_id, discord_id, guild_id),
    FOREIGN KEY (leetcode_id) REFERENCES LEETCODE_ACCOUNT(id),
    FOREIGN KEY (discord_id) REFERENCES DISCORD_ACCOUNT(id),
    FOREIGN KEY (guild_id) REFERENCES Guild(id)
);
CREATE TABLE AC_COMPLETION (
    ac_id VARCHAR(100) PRIMARY KEY,
    leetcode_id VARCHAR(100) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (leetcode_id) REFERENCES LEETCODE_ACCOUNT(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CHANNEL (
    id VARCHAR(100) PRIMARY KEY,
    guild_id VARCHAR(100) NOT NULL,
    discord_id VARCHAR(100) NOT NULL,
    FOREIGN KEY (guild_id) REFERENCES GUILD(id),
    FOREIGN KEY (discord_id) REFERENCES DISCORD_ACCOUNT(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)



